export const FETCH_QUESTIONS = 'FETCH/QUIZ/QUESTIONS';
export const FETCH_QUESTIONS_SUCCESS = `${FETCH_QUESTIONS}/SUCCESS`;
export const FETCH_QUESTIONS_ERROR = `${FETCH_QUESTIONS}/ERROR`;
export const SET_CURRENT_INDEX = `${FETCH_QUESTIONS}/INDEX`;
export const SET_SCORE = 'SET_SCORE'
export const QUIZ_STATE_KEY = 'Quiz';
